name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main,build ]
  # workflow_dispatch: allows manually kicking off a build
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Dump Environment
      run: |
       $PSVersionTable
       gci env: | ft -wrap

    - name: Do CI Build
      run: ./run.ps1 ci
